### ISSUE TITLE
PostgreSQL: pwiz doesn't generate field for primary key column

### ISSUE THREAD

**Issue by Mr-Clear** [coleifer/peewee#2875]
I tried to create model code for an existing PostgreSQL database and noticed that none of the primary key columns are present. This can be reproduced with this minimal example:

* Create PostgreSQL docker container. `docker-compose.yaml`:
```
services:
    postgres:
      image: postgres
      container_name: postgres
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_PASSWORD: pwd
      ports:
        - 5432:5432
```

* Create table:
```
CREATE TABLE public.test (
id serial4 NOT NULL,
name varchar(128) NOT NULL,
rank varchar(8) NOT NULL,
revolution_speed float NOT NULL,
CONSTRAINT test_pkey PRIMARY KEY (id)
);
```

*Create model code:
`python -m pwiz -e postgresql -u postgres -H localhost -P postgres > db_schema.py`

* Output:
```
from peewee import *
    
    database = PostgresqlDatabase('postgres', **{'host': 'localhost', 'user': 'postgres', 'password': 'pwd'})
    
    class UnknownField(object):
        def __init__(self, *_, **__): pass
    
    class BaseModel(Model):
        class Meta:
            database = database
    
    class Test(BaseModel):
        name = CharField()
        rank = CharField()
        revolution_speed = DoubleField()
    
        class Meta:
            table_name = 'test'
```

As you can see, the column `id` is not represented in class `Test`. When I create the table without `CONSTRAINT test_pkey PRIMARY KEY (id)`, it works as expected.

Peewee version: 3.17.1
PostgreSQL version: 16.2
Python version: 3.11.8
